# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='K_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.CharField(choices=[('00-03', '00-03'), ('03-06', '03-06'), ('06-09', '06-09'), ('09-12', '09-12'), ('12-15', '12-15'), ('15-18', '15-18'), ('18-21', '18-21'), ('21-24', '21-24')], max_length=3)),
                ('value', models.SmallIntegerField(default=0.0)),
            ],
        ),
    ]
