# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0002_k_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k_index',
            name='jam',
            field=models.CharField(choices=[('00-03', '00-03'), ('03-06', '03-06'), ('06-09', '06-09'), ('09-12', '09-12'), ('12-15', '12-15'), ('15-18', '15-18'), ('18-21', '18-21'), ('21-24', '21-24')], max_length=5),
        ),
    ]
