# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hujan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jumlah', models.FloatField(default=0, null=True)),
                ('kategori', models.CharField(choices=[('nihil', 'nihil'), ('sangat ringan', 'sangat ringan'), ('ringan', 'ringan'), ('sedang', 'sedang'), ('lebat', 'lebat'), ('sangat lebat', 'sangat lebat')], max_length=50)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tanggal'],
                'verbose_name_plural': 'Hujan',
            },
        ),
    ]
