# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 09:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlatTulisKantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('nama_barang', models.CharField(blank=True, max_length=100)),
                ('jumlah', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['tanggal'],
                'verbose_name_plural': 'Alat Tulis Kantor',
            },
        ),
        migrations.CreateModel(
            name='Diklat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_diklat', models.CharField(blank=True, max_length=100)),
                ('waktu_mulai', models.DateField(default=datetime.datetime.today)),
                ('waktu_berakhir', models.DateField(default=datetime.datetime.today)),
                ('lokasi', models.CharField(blank=True, max_length=100)),
                ('presentasi', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['waktu_mulai', 'nama_diklat'],
                'verbose_name_plural': 'Diklat',
            },
        ),
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nama'],
                'verbose_name_plural': 'Divisi',
            },
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nama'],
                'verbose_name_plural': 'Jabatan',
            },
        ),
        migrations.CreateModel(
            name='JadwalDinasSatpam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('keterangan', models.CharField(blank=True, choices=[(b'Pagi', b'Pagi'), (b'Siang', b'Siang'), (b'Malam', b'Malam')], max_length=100)),
            ],
            options={
                'ordering': ['tanggal'],
                'verbose_name_plural': 'Jadwal Dinas Satpam',
            },
        ),
        migrations.CreateModel(
            name='JenisAkun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_akun', models.CharField(choices=[(b'pegawai', b'Pegawai'), (b'admin', b'admin')], max_length=50)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Jenis Akun',
            },
        ),
        migrations.CreateModel(
            name='ListrikMati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('jam_mulai', models.TimeField(blank=True)),
                ('jam_berakhir', models.TimeField(blank=True)),
                ('kondisi_bbm', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('petugas_entri', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tanggal'],
                'verbose_name_plural': 'Listrik Mati',
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('judul', models.CharField(blank=True, max_length=100)),
                ('dari', models.CharField(blank=True, max_length=100)),
                ('kepada', models.CharField(blank=True, max_length=100)),
                ('isi_memo', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('petugas_entri', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tanggal'],
                'verbose_name_plural': 'Memo',
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.TextField(blank=True)),
                ('nip', models.CharField(blank=True, max_length=100)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('pangkat', models.CharField(blank=True, max_length=100)),
                ('golongan', models.CharField(blank=True, max_length=15)),
                ('pendidikan_terakhir', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_rekening', models.CharField(blank=True, max_length=100)),
                ('agama', models.CharField(blank=True, choices=[(b'Islam', b'Islam'), (b'Protestan', b'Protestan'), (b'Katolik', b'Katolik'), (b'Hindu', b'Hindu'), (b'Budha', b'Budha'), (b'Konghuchu', b'Konghuchu')], max_length=100)),
                ('status', models.CharField(blank=True, choices=[(b'PNS', b'PNS'), (b'CPNS', b'CPNS'), (b'Honor', b'Honor'), (b'Magang', b'Magang')], max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('bagian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatausaha.Divisi')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatausaha.Jabatan')),
            ],
            options={
                'ordering': ['nama'],
                'verbose_name_plural': 'Pegawai',
            },
        ),
        migrations.CreateModel(
            name='SuratKeluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('nomor_surat', models.CharField(blank=True, max_length=100)),
                ('perihal', models.CharField(blank=True, max_length=100)),
                ('tujuan', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('petugas_entri', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tanggal'],
                'verbose_name_plural': 'Surat Keluar',
            },
        ),
        migrations.CreateModel(
            name='SuratMasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.today)),
                ('nomor_surat', models.CharField(blank=True, max_length=100)),
                ('perihal', models.CharField(blank=True, max_length=100)),
                ('dari', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('petugas_entri', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tanggal'],
                'verbose_name_plural': 'Surat Masuk',
            },
        ),
        migrations.CreateModel(
            name='TugasBelajar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, choices=[(b'Diploma 4', b'Diploma 4'), (b'Sarjana', b'Sarjana'), (b'Magister', b'Magister'), (b'Doctoral', b'Doctoral')], max_length=100)),
                ('jurusan', models.CharField(blank=True, max_length=100)),
                ('perguruan_tinggi', models.CharField(blank=True, max_length=200)),
                ('tahun_mulai', models.PositiveIntegerField(blank=True, null=True)),
                ('tahun_lulus', models.PositiveIntegerField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatausaha.Pegawai')),
                ('petugas_entri', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pegawai'],
                'verbose_name_plural': 'Tugas Belajar',
            },
        ),
        migrations.AddField(
            model_name='jenisakun',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatausaha.Pegawai'),
        ),
        migrations.AddField(
            model_name='jadwaldinassatpam',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatausaha.Pegawai'),
        ),
        migrations.AddField(
            model_name='jadwaldinassatpam',
            name='petugas_entri',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diklat',
            name='nama_peserta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatausaha.Pegawai'),
        ),
        migrations.AddField(
            model_name='diklat',
            name='petugas_entri',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alattuliskantor',
            name='petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatausaha.Pegawai'),
        ),
        migrations.AddField(
            model_name='alattuliskantor',
            name='petugas_entri',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
